# Generated by Django 2.2.15 on 2020-08-05 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareduser',
            name='shared_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_boards', to=settings.AUTH_USER_MODEL),
        ),
    ]
