# Generated by Django 2.2.15 on 2020-08-06 00:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boards', '0002_auto_20200805_1437'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='board',
            unique_together={('title', 'owner')},
        ),
    ]
