# Generated by Django 2.2.15 on 2020-08-06 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_auto_20200805_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareduser',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_users', to='boards.Board'),
        ),
    ]
