# Generated by Django 2.2.15 on 2020-09-04 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_auto_20200806_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='progress_status',
            field=models.CharField(default='WORKING', max_length=50),
        ),
    ]
