# Generated by Django 2.2.15 on 2020-11-24 23:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0008_auto_20200905_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='url',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
